CREATE TABLE RWA.PMF_RWA_MAPPING (
    PMF_L5 VARCHAR2(51),
    SA_ACCOUNT__ VARCHAR2(17),
    SA_LEAF_ACCOUNT_NAME VARCHAR2(20),
    AA_ACCOUNT__ VARCHAR2(17),
    AA_LEAF_ACCOUNT_NAME VARCHAR2(20)
);
