CREATE TABLE RWA.PUG_MAPPING (
    MANAGED_SEGMENT_L2_DESCR VARCHAR2(24),
    MANAGED_SEGMENT_L3_ID NUMBER(18,0),
    MANAGED_SEGMENT_L3_DESCR VARCHAR2(43),
    MANAGED_SEGMENT_L4_ID NUMBER(18,0),
    MANAGED_SEGMENT_L4_DESCR VARCHAR2(37),
    PUG VARCHAR2(13)
);
